name: auctionvillage
description: An application for auctions

publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  another_flushbar: ^1.12.29

  auto_route: ^5.0.4

  auto_size_text: ^3.0.0

  awesome_notifications: ^0.7.3

  # badges: ^2.0.2

  bloc_concurrency: ^0.2.0

  built_collection: ^5.1.1

  built_value: ^8.4.1

  cached_network_image: ^3.2.3

  # catcher: ^0.6.9

  carousel_slider: ^4.2.1

  cloudinary_public: ^0.20.0

  connectivity_plus: ^3.0.2

  cupertino_icons: ^1.0.4

  cupertino_list_tile: ^0.2.1

  dartz: ^0.10.1

  date_format: ^2.0.7

  device_info_plus: ^8.0.0

  dio: ^4.0.4

  dio_cache_interceptor: ^3.3.1

  dio_smart_retry: ^1.4.0

  dismissible_page: ^0.7.3

  dynamic_cached_fonts: ^1.0.0

  enough_platform_widgets: ^0.5.0

  expandable: ^5.0.1

  extended_nested_scroll_view: ^5.0.0

  firebase_analytics: ^10.0.7

  firebase_core: ^2.4.0

  firebase_crashlytics: ^3.0.7

  firebase_messaging: ^14.1.4

  firebase_remote_config: ^3.0.7

  # firebase_storage: ^10.3.11

  flutter_bloc: ^8.1.1

  # flutter_colorpicker: ^1.0.3

  flutter_datetime_picker: ^1.5.1

  # flutter_downloader: ^1.8.4

  flutter_html: ^2.2.1

  flutter_masked_text2:
    git:
      url: https://github.com/Flutter-Fox/flutter_masked_text.git
      ref: hotfix-0.9.1

  # flutter_multi_formatter: ^2.8.0

  flutter_native_splash: ^2.2.16

  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: patch/1.0.5+2

  # flutter_quill: ^6.0.6+1

  # flutter_quill_extensions: ^0.1.0

  flutter_rating_bar: ^4.0.0

  flutter_screenutil:
    git:
      url: https://github.com/Flutter-Fox/flutter_screenutil.git
      ref: fix-assertion

  # flutter_spinkit: ^5.1.0

  # flutter_svg: ^1.1.5

  fluttertoast: ^8.1.2

  flutterwave_standard:
    git:
      url: https://github.com/definitelyme/flutter_standard.git
      ref: fix-exception

  freezed_annotation: ^2.2.0

  get_it: ^7.2.0

  google_fonts: ^3.0.0

  # google_sign_in: ^5.4.1

  hive_flutter:
    git:
      url: https://github.com/Flutter-Fox/hive.git
      ref: master
      path: hive_flutter/

  image_picker: ^0.8.6

  in_app_update: ^4.0.1

  inflection3: ^0.5.3+2

  injectable: ^2.1.0

  internet_connection_checker: ^1.0.0+1

  intl: ^0.17.0

  intl_phone_number_input: ^0.7.1

  isolate_handler: ^1.0.1

  json_annotation: ^4.7.0

  kt_dart: ^1.0.0

  modal_bottom_sheet: ^2.1.2

  new_version: ^0.3.1

  open_settings: ^2.0.2

  # package_info_plus: ^2.0.0

  path_provider: ^2.0.8

  permission_handler: ^10.1.0

  pinput: ^2.2.19

  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view.git
      ref: 8156907eecfa812b181a5a729d790f6d399f311b

  pretty_dio_logger: ^1.1.1

  pull_to_refresh:
    git:
      url: https://github.com/miquelbeltran/flutter_pulltorefresh.git
      ref: 6d7fbdd5b3cde242a474d66da312aac4aa892b9b

  retrofit: ^3.3.1

  retry: ^3.1.0

  rxdart: ^0.27.7

  # search_page: ^2.2.0

  # sentry_flutter: ^6.13.0

  share_plus: ^6.3.0

  shared_preferences: ^2.0.12

  shimmer: ^2.0.0

  showcaseview: ^2.0.0+1

  sliver_tools: ^0.2.8

  # sign_in_with_apple: ^4.0.0

  smooth_page_indicator: ^1.0.0+2

  socket_io_client: ^2.0.0

  # stream_channel: ^2.1.1

  # string_validator: ^0.3.0

  timeago: ^3.3.0

  timelines: ^0.1.0

  url_launcher: ^6.1.7

  uuid: ^3.0.7

dependency_overrides:
  # analyzer: ^4.7.0
  analyzer: ^5.2.0
  flutter_svg: "1.1.5"
  package_info_plus: ^2.0.0
  firebase_storage: ^11.0.1
  # sentry_flutter: "6.13.0"
  sentry_flutter: "6.18.1"

dev_dependencies:
  auto_route_generator: ^5.0.3

  build_runner: ^2.3.3

  built_value_generator: ^8.4.1

  flutter_launcher_icons: ^0.11.0

  flutter_lints: ^2.0.0

  freezed: ^2.3.2

  hive_generator:
    git:
      url: https://github.com/Flutter-Fox/hive.git
      ref: master
      path: hive_generator/

  injectable_generator: ^2.1.3

  json_serializable: ^6.5.2

  logger: ^1.1.0

  # pedantic: ^1.11.1

  retrofit_generator:
    git:
      url: https://github.com/Flutter-Fox/retrofit.dart.git
      ref: ft/app_http_client
      path: generator/

  sentry_dart_plugin: ^1.0.0-beta.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/logo/
    - assets/images/dashboard/
    - assets/images/card_logos/
    - assets/svgs/
    - assets/svgs/auth/
    - assets/svgs/logo/
    - assets/svgs/dashboard/
    - assets/svgs/profile/
    - assets/raw/

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
    - family: AVIcons
      fonts:
        - asset: assets/fonts/AVIcons.ttf
